
$scriptsDir = $HOME/.config/hypr/scripts

# Polkit (Polkit Gnome / KDE)
exec-once = $scriptsDir/Polkit.sh
exec-once = hyprpaper

# starup apps
exec-once = waybar &
exec-once = nm-applet --indicator &
exec-once = swaync &
exec-once = ags &
#exec-once = blueman-applet &

#clipboard manager
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store


# Starting hypridle to start hyprlock
exec-once = hypridle &

# Start pyprland daemon
exec-once = pypr &

