[tools]
# runtimes
node = "latest"
rust = "stable"
pnpm = "latest"

# js / ts global clis
"npm:@openai/codex" = "latest"
"npm:@google/gemini-cli" = "latest"

# python global clis
# "uv:aider-chat" = "latest"
# "uv:edge-tts" = "latest"
# "uv:huggingface-hub" = "latest"

# rust global clis

# GitHub‑provided binaries (no compilation)
"github:rtk-ai/rtk" = "latest"

[settings]
experimental = true
jobs = 4
legacy_version_file = true
idiomatic_version_file_enable_tools = ["python", "node", "rust", "uv", "pnpm"]

[settings.cargo]
binstall = true
