[tools]
# runtimes
node = "22"
python = "3.12"
rust = "stable"
uv = "latest"
pnpm = "latest"

# js / ts global clis
"npm:@openai/codex" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@letta-ai/letta-code" = "latest"

# python global clis
"uv:aider-chat" = "latest"
"uv:edge-tts" = "latest"
"uv:huggingface-hub" = "latest"

# rust global clis
"cargo:git-delta" = "latest"

[settings]
experimental = true
jobs = 4
legacy_version_file = true
idiomatic_version_file_enable_tools = ["python", "node", "rust", "uv", "pnpm"]
pipx_uvx = true

[settings.cargo]
binstall = true
