[mgr]
ratio = [1, 4, 3]
linemode = "size_and_mtime"
show_hidden = false

[tasks]
image_alloc = 1073741824

[spot]
title = { fg = "green" }
tbl_col = { fg = "blue" }

[opener]
edit = [
  { run = 'nvim %s', block = true, for = "unix" },
]
play = [
  { run = 'mpv %s', orphan = true, for = "unix" },
]
open = [
  { run = 'xdg-open %s', orphan = true, for = "unix" },
]

[open]
rules = [
  { mime = "text/*", use = "edit" },
  { mime = "video/*", use = "play" },
  { url = "*.json", use = "edit" },
  { url = "*.html", use = ["open", "edit"] },
]
