# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Obsidian: float, 80% size, centered, on special workspace
windowrule = match:class ^([Oo]bsidian)$, float on
windowrule = match:class ^([Oo]bsidian)$, size (monitor_w*.90) (monitor_h*.90)
windowrule = match:class ^([Oo]bsidian)$, center on
windowrule = match:class ^([Oo]bsidian)$, workspace special:obsidian

windowrule = match:class ^(yazi)$, float on
windowrule = match:class ^(yazi)$, size (monitor_w*.80) (monitor_h*.80)
windowrule = match:class ^(yazi)$, center on
windowrule = match:class ^(yazi)$, workspace special:yazi

# Google Calendar: float, 65% width, 85% height, centered, on special workspace
windowrule = match:title ^(Google Calendar)(.*)$, float on
windowrule = match:title ^(Google Calendar)(.*)$, size (monitor_w*0.65) (monitor_h*0.85)
windowrule = match:title ^(Google Calendar)(.*)$, center on
windowrule = match:title ^(Google Calendar)(.*)$, workspace special:calendar

