
# Sourcing external config files
$configs = $HOME/.config/hypr/configs # Default Configs directory path

source=$configs/Keybinds.conf # Pre-configured keybinds

$UserConfigs = $HOME/.config/hypr/UserConfigs
source= $UserConfigs/Startup_Apps.conf
source= $UserConfigs/ENVariables.conf
source= $UserConfigs/Laptops.conf
source= $UserConfigs/WindowRules.conf
source= $UserConfigs/UserDecorations.conf
source= $UserConfigs/UserAnimations.conf
source= $UserConfigs/UserKeybinds.conf
source= $UserConfigs/UserSettings.conf
