#
# /etc/pacman.conf
# Optimized for speed + beautiful output
#

[options]

# -------------------------------------------------
# Core
# -------------------------------------------------
Architecture = auto
CheckSpace
Color
ILoveCandy
VerbosePkgLists

# -------------------------------------------------
# Performance
# -------------------------------------------------
ParallelDownloads = 15
DownloadUser = alpm

# External downloader (FASTEST)

# XferCommand = /usr/bin/aria2c --allow-overwrite=true --continue=true --file-allocation=none --max-connection-per-server=16 --min-split-size=5M --max-tries=3 --timeout=10 --console-log-level=warn --summary-interval=1 --dir=/ --out %o %u


# -------------------------------------------------
# Package Protection
# -------------------------------------------------
HoldPkg = pacman glibc

# Ignore packages you manage manually
IgnorePkg = linux linux-headers libreoffice-still blender qgis

# -------------------------------------------------
# Security
# -------------------------------------------------
SigLevel = Required DatabaseNever
LocalFileSigLevel = Optional

# -------------------------------------------------
# Paths (defaults)
# -------------------------------------------------
#RootDir     = /
#DBPath      = /var/lib/pacman/
#CacheDir    = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
#GPGDir      = /etc/pacman.d/gnupg/
#HookDir     = /etc/pacman.d/hooks/

# =================================================
# REPOSITORIES
# =================================================

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# =================================================
# THIRD PARTY
# =================================================

[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist


# =================================================
# OPTIONAL (DISABLED)
# =================================================

#[core-testing]
#Include = /etc/pacman.d/mirrorlist

#[extra-testing]
#Include = /etc/pacman.d/mirrorlist

#[multilib-testing]
#Include = /etc/pacman.d/mirrorlist

#[blackarch]
#Include = /etc/pacman.d/blackarch-mirrorlist

