monitor = , preferred, auto, 1

general {
    # gaps
    gaps_in = 0
    gaps_out = 0
    gaps_workspaces = 0

    # borders
    border_size = 1
    col.active_border = rgba(ffffffaa)
    col.inactive_border = rgba(00000000)

    # behavior
    resize_on_border = true
    no_focus_fallback = true
    allow_tearing = true

    layout = dwindle

    snap {
        enabled = true
    }
}

decoration {
    rounding = 0
    active_opacity = 1.0
    inactive_opacity = 1.0

    blur {
        enabled = false
    }

    shadow {
        enabled = false
    }
}

animations {
    enabled = false
}
# animations {
#     enabled = true
#     animation = windows, 1, 2, default
#     animation = fade, 1, 2, default
#     animation = workspaces, 1, 2, default
# }
#
dwindle {
    pseudotile = true
    preserve_split = true
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vfr = true
    vrr = 1
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
}

input {
    follow_mouse = 1
    sensitivity = 1

    touchpad {
        natural_scroll = true
    }
}


