# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Obsidian: float, 80% size, centered, on special workspace
windowrule = match:class ^(obsidian)$, float on
windowrule = match:class ^(obsidian)$, size (monitor_w*.80) (monitor_h*.80)
windowrule = match:class ^(obsidian)$, center on
windowrule = match:class ^(obsidian)$, workspace special:obsidian

windowrule = match:class ^(yazi)$, float on
windowrule = match:class ^(yazi)$, size (monitor_w*.80) (monitor_h*.80)
windowrule = match:class ^(yazi)$, center on
windowrule = match:class ^(yazi)$, workspace special:yazi

