# Native Wayland
--ozone-platform-hint=wayland

# GTK4 integration
--gtk-version=4

# Wayland IME support
--enable-wayland-ime

# GNOME Keyring
--password-store=gnome-libsecret

# Ignore Chrome GPU blacklist
--ignore-gpu-blocklist

# GPU rasterization
# --enable-gpu-rasterization

# Lower copy overhead
--enable-zero-copy

# Vulkan rendering
# --use-angle=vulkan

# Experimental Vulkan  # video player failing
# --enable-features=Vulkan

# WebGPU
# --enable-unsafe-webgpu

# Advanced WebGPU
# --enable-webgpu-developer-features

# Future web APIs
--enable-experimental-web-platform-features

# Faster downloads
--enable-features=ParallelDownloading


# Touchpad gestures
#--enable-features=TouchpadOverscrollHistoryNavigation

# Saved tab groups
--enable-features=TabGroupsSave


# Site isolation
--enable-features=StrictOriginIsolation

# Gemini core
--enable-features=Glic

# Gemini actions
--enable-features=GlicActor

# Gemini PDF assistant
--enable-features=GlicPdfSummarize

# Gemini selections
--enable-features=GlicSelectionPrompt

# Gemini tab grouping
--enable-features=GlicTabGroups

# Gemini contextual hints
--enable-features=GlicContextualCueing

# Gemini launcher
--enable-features=GlicLauncher

# Gemini entrypoint
--enable-features=GlicPinnedEntryPoint

# Gemini settings page
--enable-features=GlicSettingsPage

# Force Gemini rollout
--force-fieldtrials=Glic/Enabled/


# force dark mode
#--enable-force-dark
